export let videos = {
  video1: {
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    channelName: "Marques Brownlee",
    channelProfile: "/assets/channels/channel-1.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-1.webp",
    views: "3.4M",
    time: "6 months",
    duration: "14:20",
  },
  video2: {
    title: "Try Not To Laugh Challenge #9",
    channelName: "Markiplier",
    channelProfile: "/assets/channels/channel-2.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-2.webp",
    views: "19M",
    time: "4 years",
    duration: "8:22",
  },
  video3: {
    title: "Crazy Tik Toks Taken Moments Before DISASTER",
    channelName: "SSSniperWolf",
    channelProfile: "/assets/channels/channel-3.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-3.webp",
    views: "12M",
    time: "1 year",
    duration: "9:13",
  },
  video4: {
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    channelName: "Veritasium",
    channelProfile: "/assets/channels/channel-4.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-4.webp",
    views: "18M",
    time: "4 months",
    duration: "22:09",
  },
  video5: {
    title: "Kadane's Algorithm to Maximum Sum Subarray Problem",
    channelName: "CS Dojo",
    channelProfile: "/assets/channels/channel-5.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-5.webp",
    views: "519K",
    time: "5 years",
    duration: "11:17",
  },
  video6: {
    title: "Anything You Can Fit In The Circle I’ll Pay For",
    channelName: "MrBeast",
    channelProfile: "/assets/channels/channel-6.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-6.webp",
    views: "141M",
    time: "1 year",
    duration: "19:59",
  },
  video7: {
    title:
      "Why Planes Don't Fly Over TibetTalking Tech and AI with Google CEO Sundar Pichai!",
    channelName: "RealLifeLore",
    channelProfile: "/assets/channels/channel-7.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-7.webp",
    views: "6.6M",
    time: "1 year",
    duration: "10:13",
  },
  video8: {
    title: "Inside The World's Biggest Passenger Plane",
    channelName: "Tech Vision",
    channelProfile: "/assets/channels/channel-8.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-8.webp",
    views: "3.7M",
    time: "10 months",
    duration: "7:12",
  },
  video9: {
    title: "The SECRET to Super Human STRENGTH",
    channelName: "ThenX",
    channelProfile: "/assets/channels/channel-9.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-9.webp",
    views: "20M",
    time: "3 years",
    duration: "13:17",
  },
  video10: {
    title: "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
    channelName: "Business Insider",
    channelProfile: "/assets/channels/channel-10.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-10.webp",
    views: "14M",
    time: "1 year",
    duration: "7:53",
  },
  video11: {
    title: "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
    channelName: "Destination Tips",
    channelProfile: "/assets/channels/channel-11.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-11.webp",
    views: "3M",
    time: "1 year",
    duration: "4:10",
  },
  video12: {
    title: "What would happen if you didn’t drink water? - Mia Nacamulli",
    channelName: "TED-Ed",
    channelProfile: "/assets/channels/channel-12.jpeg",
    thumbnail: "/assets/thumbnails/thumbnail-12.webp",
    views: "12M",
    time: "5 years",
    duration: "4:51",
  },
};
